// Matches user.go
export const ROLES = {
  SYSTEM_ADMIN: "REFTRAIL_ADMIN",
  BOOKING_TEAM: "BOOKING_TEAM",
} as const;

export const ALL_STATUSES = [
  'READY_TO_BOOK', '1ST_CALL_COMPLETE', '2ND_CALL_COMPLETE', '3RD_CALL_COMPLETE',
  'BOOKED', 'UNABLE_TO_CONTACT', 'PATIENT_TO_CALL_BACK', 'DECLINED', 'SUSPENDED', 'CLOSED'
] as const;

export const STATUS_RULES: Record<string, string[]> = {
  READY_TO_BOOK: ['1ST_CALL_COMPLETE', 'UNABLE_TO_CONTACT', 'DECLINED', 'BOOKED'],
  '1ST_CALL_COMPLETE': ['2ND_CALL_COMPLETE', 'UNABLE_TO_CONTACT', 'DECLINED', 'BOOKED'],
  '2ND_CALL_COMPLETE': ['3RD_CALL_COMPLETE', 'UNABLE_TO_CONTACT', 'DECLINED', 'BOOKED'],
  '3RD_CALL_COMPLETE': ['UNABLE_TO_CONTACT', 'DECLINED', 'BOOKED'],
  PATIENT_TO_CALL_BACK: ['1ST_CALL_COMPLETE', 'BOOKED', 'DECLINED', 'SUSPENDED', 'CLOSED'],
  UNABLE_TO_CONTACT: ['READY_TO_BOOK'],
  BOOKED: [],
  DECLINED: [],
  CLOSED: [],
} as const;